### ISSUE TITLE
Generator missing some files?

### ISSUE THREAD

**Issue by danscrima** [alduro/generator-flux-webapp#3]
This looks really awesome, but the generator is having some issue when I run **yo flux-webapp**

```
fs.js:695
  return binding.stat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/usr/lib/node_modules/generator-flux-webapp/app/templates/src/pages/index.jsx'
    at Object.fs.statSync (fs.js:695:18)
    at Env.File.copy (/usr/lib/node_modules/generator-flux-webapp/node_modules/yeoman-generator/node_modules/file-utils/lib/file.js:305:14)
    at Env.copy (/usr/lib/node_modules/generator-flux-webapp/node_modules/yeoman-generator/node_modules/file-utils/lib/env.js:32:32)
    at yeoman.generators.Base.extend.writing.app (/usr/lib/node_modules/generator-flux-webapp/app/index.js:55:16)
    at /usr/lib/node_modules/generator-flux-webapp/node_modules/yeoman-generator/lib/base.js:395:14
    at processImmediate [as _immediateCallback] (timers.js:345:15)

```

**Comment by kiddhustle** [comment]
Hi I've recently install this generator and I still see the same issue. Any idea why?

The version I seem to be using is: generator-flux-webapp@0.1.3

**Comment by zycbobby** [comment]
Hi, I have tried but still meet this problem:

> ➜  hello-flux  yo flux-webapp

     _-----_
    |       |    .--------------------------.
    |--(o)--|    |      Welcome to the      |
   `---------´   |   incredible FluxWebapp  |
    ( _´U`_ )    |        generator!        |
    /___A___\    '--------------------------'
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? Your project name: HelloFlux
fs.js:568
  function strWrapper(err, written) {
                ^
Error: ENOENT, no such file or directory '/usr/local/lib/node_modules/generator-flux-webapp/app/templates/src/pages/index.jsx'
    at Error (native)
    at Object.fs.openSync (fs.js:502:18)
    at module.exports (/usr/local/lib/node_modules/generator-flux-webapp/node_modules/yeoman-generator/node_modules/isbinaryfile/index.js:14:25)
    at Env.File.copy (/usr/local/lib/node_modules/generator-flux-webapp/node_modules/yeoman-generator/node_modules/file-utils/lib/file.js:301:42)
    at Env.copy (/usr/local/lib/node_modules/generator-flux-webapp/node_modules/yeoman-generator/node_modules/file-utils/lib/env.js:33:32)
    at yeoman.generators.Base.extend.writing.app (/usr/local/lib/node_modules/generator-flux-webapp/app/index.js:55:16)
    at /usr/local/lib/node_modules/generator-flux-webapp/node_modules/yeoman-generator/lib/base.js:395:14
    at processImmediate [as _immediateCallback] (timers.js:358:17)

I have checked '/usr/local/lib/node_modules/generator-flux-webapp/app/templates/src/pages/index.jsx', but there is '/usr/local/lib/node_modules/generator-flux-webapp/app/templates/src/pages/Index.jsx'

**Comment by sanketmaru** [comment]
This issue is still occurring to me as well as new release hasn't been published.  Please publish new release so the generator can be used.
